version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            touch .env
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run app bash -c "python manage.py createdb test"
            docker-compose run app bash -c "python manage.py test"
