version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: 'idea360'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  idea360:
    image: vsokoltsov/idea360
    container_name: idea360
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DEFAULT_REQUIREMENTS=development.txt
    command: bash -c "python manage.py runserver --host 0.0.0.0"
    env_file: ./.env
    volumes:
      - .:/idea360
    ports:
     - "5000:5000"
    depends_on:
      - postgres

volumes:
  pg_data:
