"""empty message

Revision ID: f32da8ea04d9
Revises: 333e49c20571
Create Date: 2017-10-24 23:43:46.160667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32da8ea04d9'
down_revision = '333e49c20571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_digest',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_digest',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
