"""empty message

Revision ID: f4cf3e97f574
Revises: 9f855b375b7d
Create Date: 2017-10-16 00:49:46.589024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cf3e97f574'
down_revision = '9f855b375b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_digest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_digest')
    # ### end Alembic commands ###
